# Generated by Django 3.2 on 2021-04-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('file_id', models.TextField(verbose_name='ID комикса')),
                ('cover_id', models.TextField(verbose_name='ID обложки комикса')),
                ('colpage_pdf', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('count_views', models.PositiveIntegerField(verbose_name='Количество просмотров')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(verbose_name='ID пользователя')),
                ('type_user', models.TextField(verbose_name='Права пользователя')),
                ('count_reads', models.PositiveIntegerField(verbose_name='Количество прочтений')),
            ],
        ),
    ]
